### ISSUE TITLE
第二个脚本似乎用不起，求解决

### ISSUE THREAD

**Issue by ishkong** [tangrela/k1kmz#1]
Traceback (most recent call last):
  File "auto_post.py", line 9, in <module>
    wb=Weibo()
  File "/root/caiji/wb_upload.py", line 32, in __init__
    self._login()
  File "/root/caiji/wb_upload.py", line 154, in _login
    with open(self.cookie_file,'rb') as f:
IOError: [Errno 2] No such file or directory: 'wbcookies

**Comment by tangrela** [comment]
脚本同目录建一个wbcookies空文件
