### ISSUE TITLE
When I running python auto_post.py

### ISSUE THREAD

**Issue by cclylycc** [tangrela/k1kmz#2]
Traceback (most recent call last):
  File "auto_post.py", line 9, in <module>
    wb=Weibo()
  File "/root/k1kmz-master/wb_upload.py", line 32, in __init__
    self._login()
  File "/root/k1kmz-master/wb_upload.py", line 155, in _login
    cookies_dict=pickle.load(f)

**Comment by tangrela** [comment]
fix
